
[dialogs]
confirm = "Confirm?"
error   = "Error"
ok      = "Ok"
cancel  = "Cancel"

[dialogs.entity]
add    = "Add chapter"
edit   = "Edit chapter"
delete = "Chapter will be deleted"
exist  = "Chapter already exists"

name   = "Name"
title  = "Title"
group  = "Group"

[dialogs.text]
new    = "Book will be overwritten if not saved"


[navbar.file]
title = "File"
new   = "New"
open  = "Open..."
save  = "Download"

[navbar.book]
title = "Book"
graph = "View graph"

[navbar.export]
title = "Export"
docx  = "Word (.docx)"
fodt  = "Libreoffice (.fodt)"
md    = "Markdown (.md)"
json  = "Json"
vuejs = "Vue.js"

[navbar.help]
title     = "Help"
guide     = "Guide"
guidefile = "guide-en.pdf" 
forum     = "Lgl forum"
about     = "About"

[sidemenu]
toggle    = "Toggle sidemenu"
chapters  = "Chapters"
linkshere = "Links to"

[sidemenu.actions]
add      = "Add entity (ctrl+R)"
edit     = "Edit entity (ctrl+E)"
delete   = "Delete entity (ctrl+D)"


[editor.buttons]
quicklink = "Link to the first avaiable chapter (ctrl+K)"
link      = "Add link (ctrl+L)"


[about]
contact = "Contact me"
text = """
Lgcjs is a gamebook web editor developed by <b>Luca Fabbian</b> with support of Lgl community,
based on LibroGameCreator3 by <b>Matteo Poropat</b>."""
