
[dialogs]
confirm = "Confermi?"
error   = "Errore"
ok      = "Ok"
cancel  = "Annulla"

[dialogs.entity]
add    = "Aggiungi entità"
edit   = "Modifica entità"
delete = "L'entità verrà eliminata"
exist  = "Questa entità esiste già"

name   = "Nome"
title  = "Titolo"

[dialogs.text]
new    = "Il libro verrà sovrascritto se non salvato"


[navbar.file]
title = "File"
new   = "Nuovo"
open  = "Apri..."
save  = "Download"

[navbar.view]
title = "Visualizza"
graph = "Grafico libro"

[navbar.export]
title = "Esporta"
docx  = "Word (.docx)"
fodt  = "Libreoffice (.fodt)"
md    = "Markdown (.md)"
json  = "Json"
vuejs = "Vue.js"

[navbar.help]
title     = "Aiuto"
guide     = "Guida"
guidefile = "guide-it.pdf" 
forum     = "Forum Lgl"
about     = "Info"

[sidemenu]
toggle   = "Apri menu laterale"
chapters = "Paragrafi"
linkshere = "Link al par."

[sidemenu.actions]
add      = "Aggiungi entità (ctrl+R)"
edit     = "Modifica entità (ctrl+E)"
delete   = "Elimina entità (ctrl+D)"


[editor.buttons]
quicklink  = "Link al primo paragrafo disponibile (ctrl+K)"
link  = "Aggiungi link (ctrl+L)"


[about]
contact = "Contattami"
text = """
Lgcjs è un editor di librogame sviluppato da <b>Luca Fabbian</b> con il supporto della community di Lgl,
basato su LibroGameCreator3 di <b>Matteo Poropat</b>."""

[book]
guide = ""
welcome = """
# Welcome
author: 


"""