
[dialogs]
confirm = "Confirm?"


[navbar]
"file.title" = "File"
"file.items" = {new = "New", open = "Open...", save = "Save"}

"edit.title" = "Edit"
"edit.items" = { }

"code.title" = "Code"
"code.items" = {togglecode = "Show/hide code tools", jsexport = "JSExport book"}

"help.title" = "Help"
"help.items" = {guide = "Guide", forum = "Lgl forum", about = "About"}
