
[dialogs]
confirm = "Confirm?"


[navbar]
"file.title" = "File"
"file.items" = {new = "New", open = "Open...", save = "Save"}

"edit.title" = "Edit"
"edit.items" = { }

"code.title" = "Code"
"code.items.togglecode" = "Show/hide code tools"
"code.items.json"       = "Export json"
"code.items.appjs"      = "Export app.js"

"help.title" = "Help"
"help.items" = {guide = "Guide", forum = "Lgl forum", about = "About"}
